oncall/urls.py
from django.urls import path
from oncall import views

app_name = "oncall"

urlpatterns = [
    path("", views.oncall_log_view, name="oncall_log"),
    path("<int:id>/", views.oncall_detail, name="oncall_detail"),
    path("call/create/", views.call_create_view, name="oncall_log_create"),
    path("call/colors/", views.get_domain_colors, name="oncall_colors"),
    path("call/upload/", views.call_upload_list_post, name="oncall_upload_list_post"),
    path("call/stat/by_function/", views.call_stat_by_function, name="oncall_stat_by_function"),
    path("call/stat/duration/", views.call_duration_histogram, name="oncall_duration_histogram"),
    path("call/stat/time-of-day/", views.call_time_of_day_histogram, name="oncall_time_of_day_histogram"),
    path("call/stat/daily-cumulative/", views.call_daily_cumulative, name="oncall_daily_cumulative"),
    path("ajax/oncall_log", views.oncall_log_contacts_json, name="oncall_log_json"),
    path("<int:id>/edit/", views.oncall_update_view, name="oncall_log_edit"),
]

shifter/urls.py
from django.contrib import admin
from django.urls import include, path
import notifications.urls

urlpatterns = [
    path("planning/", include("shifts.urls.main")),
    path("", include("shifts.urls")),
    path("studies/", include("studies.urls")),
    path("oncall/", include("oncall.urls")),
    path("ajax/", include("shifts.urls.ajax")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),  # new
    path("desiderata/", include("shifts.urls.desiderata")),
    path("inbox/notifications/", include(notifications.urls, namespace="notifications")),
]

shifts/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=25)
    username.widget.attrs = {"size": 8}
    password = forms.CharField(max_length=30, widget=forms.PasswordInput)
    password.widget.attrs = {"size": 8}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

shifts/views/ajax.py
from django.http import HttpResponse, JsonResponse
from django.http import HttpRequest
from django.db.models import Count, Q
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_safe

from shifts.exchanges import is_valid_for_hours_constraints_from_market
from shifts.io import write_csv
from shifts.models import *
from studies.models import *
import datetime
from members.models import Team
from assets.models import AssetBooking
from shifts.hrcodes import get_public_holidays, MAX_HOURS_SCHEDULED_PER_CYCLE
from shifts.hrcodes import OB1, OB2, OB3, OB4, NWH, LC1, LC2, ELC, BTP_OR_BTB, OTT_OR_OTW, OB1_WEIGHT, OB2_WEIGHT, OB3_WEIGHT, OB4_WEIGHT
from shifts.models import SIMPLE_DATE
from shifts.hrcodes import get_date_code_counts
from shifter.settings import DEFAULT_SPECIAL_SHIFT_ROLES, DEFAULT_SHIFT_SLOT
from shifts.workinghours import find_daily_rest_time_violation, find_weekly_rest_time_violation, get_hours_break, get_days_of_week, last_day_of_month
import json
from watson import search as watson
from guardian.shortcuts import get_objects_for_user
from django.core.exceptions import PermissionDenied
from shifts.workinghours import get_working_hours as get_working_hours_yearly


def _get_member(request: HttpRequest):
    member_id = request.GET.get("member", -1)
    if member_id == -1:
        member = request.user
    else:
        member = Member.objects.filter(id=member_id).first()
    return member


def _get_revision(request: HttpRequest):
    revision = int(request.GET.get("revision", -1))
    if revision == -1:
        revision = Revision.objects.filter(valid=True).order_by("-number").first()
    else:
        revision = Revision.objects.get(number=revision)
    return revision


def _get_scheduled_shifts(request: HttpRequest):
    start_date = request.GET.get("start", None)
    end_date = request.GET.get("end", None)
    if start_date is None or end_date is None:
        return HttpResponse({}, content_type="application/json", status=500)
    start = datetime.datetime.fromisoformat(start_date).date() - datetime.timedelta(days=1)
    end = datetime.datetime.fromisoformat(end_date).date() + datetime.timedelta(days=1)
    filter_dic = {
        "revision": Revision.objects.filter(valid=True).order_by("-number").first(),
        "date__lte": end,
        "date__gte": start,
        "member": _get_member(request),
    }
    return Shift.objects.filter(**filter_dic)


def _get_companions_shift(member: Member, base_scheduled_shifts):
    filteredCompanions = []
    filter_dic = {
        "date__in": [s.date for s in base_scheduled_shifts],
        "revision__in": [s.revision for s in base_scheduled_shifts],
        "role": None,
    }
    future_companion_shifts = Shift.objects.filter(**filter_dic).filter(~Q(member=member))
    future_companion_exact_shifts = [d.start for d in base_scheduled_shifts]
    for d in future_companion_shifts:
        if d.start in future_companion_exact_shifts:
            filteredCompanions.append(d)
    return filteredCompanions


def _trim4vis(item, default=""):
    return item if item > 0 else default


@require_safe
@login_required
def get_user_events(request: HttpRequest) -> HttpResponse:
    base_scheduled_shifts = _get_scheduled_shifts(request)
    calendar_events = [d.get_shift_as_json_event() for d in base_scheduled_shifts]
    revisionNext = request.GET.get("revision_next", default="-1")
    revisionNext = int(revisionNext)
    show = request.GET.get("show", None)
    show = False if show == "false" else True
    if revisionNext != -1:
        revisionNext = Revision.objects.get(number=revisionNext)
        future_scheduled_shifts = Shift.objects.filter(member=_get_member(request), revision=revisionNext)
        for d in future_scheduled_shifts:
            calendar_events.append(d.get_planned_shift_as_json_event())
    withCompanion = request.GET.get("companion", default=None)
    withCompanion = True if withCompanion == "true" else False
    if withCompanion:
        for d in _get_companions_shift(_get_member(request), base_scheduled_shifts):
            calendar_events.append(d.get_shift_as_json_event())
    if not show:
        calendar_events = []
    return HttpResponse(json.dumps(calendar_events), content_type="application/json")


@require_safe
@login_required
def get_users_events(request: HttpRequest) -> HttpResponse:
    users_requested = request.GET.get("users", "")
    users_requested = users_requested.split(",")
    users_requested = [int(x) for x in users_requested] if users_requested != [""] else []

    start_date = request.GET.get("start", None)
    end_date = request.GET.get("end", None)
    all_roles = request.GET.get("all_roles", None)
    all_states = request.GET.get("all_states", None)
    campaigns = request.GET.get("campaigns", None)
    revision = _get_revision(request)
    revisionNext = request.GET.get("revision_next", default="-1")

    if start_date is None or end_date is None or all_roles is None or campaigns is None or revision is None:
        return HttpResponse({}, content_type="application/json", status=500)

    campaigns = campaigns.split(",")
    campaigns = [int(x) for x in campaigns] if campaigns != [""] else []
    all_roles = True if all_roles == "true" else False
    all_states = True if all_states == "true" else False
    start = datetime.datetime.fromisoformat(start_date).date() - datetime.timedelta(days=1)
    end = datetime.datetime.fromisoformat(end_date).date() + datetime.timedelta(days=1)
    scheduled_campaigns = Campaign.objects.filter(revision=revision).filter(id__in=campaigns)

    filter_dic = {
        "date__gt": start,
        "date__lt": end,
        "revision": revision,
        "campaign__in": scheduled_campaigns,
        "member_id__in": users_requested,
        "is_cancelled": False,
        "is_active": True,
    }

    isRotaMaker = request.user.team in get_objects_for_user(request.user, "members.view_desiderata")
    if not isRotaMaker:
        filter_dic["is_cancelled"] = False
        filter_dic["is_active"] = True

    if all_states:
        filter_dic.pop("is_cancelled")
        filter_dic.pop("is_active")

    scheduled_shifts = Shift.objects.filter(**filter_dic).order_by("date", "slot__hour_start", "member__role__priority")
    if not all_roles:
        scheduled_shifts = scheduled_shifts.filter(
            Q(role=None) | Q(role__in=[one for one in ShiftRole.objects.filter(abbreviation__in=DEFAULT_SPECIAL_SHIFT_ROLES)])
        )
    calendar_events = [d.get_shift_as_json_event() for d in scheduled_shifts]

    revisionNext = int(revisionNext)
    if revisionNext != -1:
        revisionNext = Revision.objects.get(number=revisionNext)
        future_scheduled_shifts = Shift.objects.filter(member_id__in=users_requested, revision=revisionNext)
        for d in future_scheduled_shifts:
            calendar_events.append(d.get_planned_shift_as_json_event())

    return HttpResponse(json.dumps(calendar_events), content_type="application/json")


@require_safe
def get_events(request: HttpRequest) -> HttpResponse:
    start_date = request.GET.get("start", None)
    end_date = request.GET.get("end", None)
    all_roles = request.GET.get("all_roles", None)
    campaigns = request.GET.get("campaigns", None)
    revision = request.GET.get("revision", None)
    team_id = request.GET.get("team", -1)

    if start_date is None or end_date is None or all_roles is None or campaigns is None or revision is None:
        return HttpResponse({}, content_type="application/json", status=500)

    campaigns = campaigns.split(",")
    campaigns = [int(x) for x in campaigns] if campaigns != [""] else []
    all_roles = True if all_roles == "true" else False
    start = datetime.datetime.fromisoformat(start_date).date() - datetime.timedelta(days=1)
    end = datetime.datetime.fromisoformat(end_date).date() + datetime.timedelta(days=1)
    revision = int(revision)

    if revision == -1:
        revision = Revision.objects.filter(valid=True).order_by("-number").first()
    else:
        revision = Revision.objects.get(valid=True, number=revision)
    scheduled_campaigns = Campaign.objects.filter(revision=revision).filter(id__in=campaigns)

    filter_dic = {
        "date__gt": start,
        "date__lt": end,
        "revision": revision,
        "campaign__in": scheduled_campaigns,
    }
    isRotaMaker = False
    if request.user.is_authenticated:
        isRotaMaker = request.user.team in get_objects_for_user(request.user, "members.view_desiderata")
    if not isRotaMaker:
        filter_dic["is_cancelled"] = False
        filter_dic["is_active"] = True

    if int(team_id) > 0:
        team = Team.objects.get(id=team_id)
        filter_dic["member__team"] = team
    scheduled_shifts = Shift.objects.filter(**filter_dic).order_by("date", "slot__hour_start", "member__role__priority")
    if not all_roles:
        scheduled_shifts = scheduled_shifts.filter(
            Q(role=None) | Q(role__in=[one for one in ShiftRole.objects.filter(abbreviation__in=DEFAULT_SPECIAL_SHIFT_ROLES)])
        )

    calendar_events = [d.get_shift_as_json_event() for d in scheduled_shifts]

    return HttpResponse(json.dumps(calendar_events), content_type="application/json")


@require_safe
def get_team_events(request: HttpRequest) -> HttpResponse:
    # TODO Remove the hardcoded dates here BUT remember!
    # TODO make this Model based AFTER other branches are merged - to avoid DB model conflicts.
    days = get_days_of_week(17, year=2024) + get_days_of_week(20, year=2024) + get_days_of_week(21, year=2024) + get_days_of_week(35, year=2024)
    calendar_events = [
        {"start": d.strftime(format=SIMPLE_DATE), "end": d.strftime(format=SIMPLE_DATE), "overlap": True, "color": "#FFE7CB", "display": "background"}
        for d in days
    ]
    return HttpResponse(json.dumps(calendar_events), content_type="application/json")


@require_safe
def get_holidays(request: HttpRequest) -> HttpResponse:

shifts/views/errors.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, "404.html", {})


def error_500(request):
    return render(request, "500.html", {})

shifts/templates/layout/calendar_tools_off_canvas.html
<div class="offcanvas offcanvas-start" tabindex="-1" id="tools_off_canvas" aria-labelledby="tools_off_canvas_label">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="tools_off_canvas_label">Calendar Tools</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body p-2">
        <div class="container-fluid p-0">
            {% if hide_campaign_selection is not True %}
            <div class="row my-2">
                <label for="displayed_campaigns" class="form-label">
                    <strong>Selected Campaign(s):</strong>
                    <select class="js-states form-control displayed_campaigns" id="displayed_campaigns" multiple="multiple">
                        {% for c in campaigns %}
                        <option id="campaign{{c.id}}" value="{{c.id}}" {%if c in scheduled_campaigns_list%} selected {%endif%}>{{c}} - <small><strong>{{c.date_start}} - {{c.date_end}}</strong></small></option>
                        {% endfor %}
                    </select>
                </label>
            </div>
            {%  endif %}
            {%  if hide_extra_role_selection is not True %}
            <div class="row m-2 p-2">
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="all_roles">
                    <label class="form-check-label" for="all_roles">Display additional roles assigned to the specific shift, e.g.
                        <strong>Office</strong>,  <strong>Conferences</strong>,  <strong>Trainings</strong>.</label>
                </div>
            </div>
            {% endif %}
            {%  if allow_see_canceled is True %}
            <div class="row m-2 p-2">
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="all_states">
                    <label class="form-check-label" for="all_states">Display all shifts including <strong>inactive and cancelled</strong>.</label>
                </div>
            </div>
            {% endif %}
            {% if show_companion is True %}
            <div class="row m-2 p-2">
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="show_companion">
                    <label class="form-check-label" for="show_companion">Display additional shift companion </label>
                </div>
            </div>
            {% endif %}
            <div class="row m-2 p-2">
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="show_studies" {% if hide_studies is not True %}checked{%endif%}>
                    <label class="form-check-label" for="show_studies">Show studies.</label>
                </div>
            </div>
            <hr>
            <div class="row mt-2 mx-0">
                <h5>Slots Legend</h5>
                {%for s in slots%}
                <div class="d-flex justify-content-between align-items-center mb-2" style="background-color:{{s.color_in_calendar}}; color:#FFFFFF; padding: 0.5em; border-radius: 0.25em;">
                    <span>{{s.name}} <strong>({{s.abbreviation}})</strong></span>
                    <span><strong>{{s.hour_start}}</strong> - <strong>{{s.hour_end}}</strong></span>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<style>

@media (max-width: 576px) {
    .offcanvas {
        width: 100% !important;
    }
}

@media (min-width: 577px) {
    .offcanvas {
        width: 576px !important;
    }
}

</style>

shifts/templates/layout/footer.html
<footer class="{% if SHIFTER_TEST_INSTANCE %}footer-dev{% else %}footer{% endif %} d-none d-md-block">
    <div class="container text-center">
        <div class="row align-items-center">
            <div class="col-md-4">
                <a class="link-secondary" target="_blank" href="{{APP_REPO}}/-/issues/new">Submit ideas/bugs/requests</a>
            </div>
            <div class="col-md-4">
                {{ APP_NAME }} -
                <a class="link-secondary" target="_blank" href="{{APP_REPO}}/-/blob/master/CHANGELOG.md">{{APP_GIT_TAG}}</a>
            </div>
            <div class="col-md-4">
                <a class="link-secondary" href="{% url 'dates' %}">Environment configuration</a>
            </div>
        </div>
    </div>
</footer>

shifts/templates/layout/navbar.html
{% load static %}
{% load notifications_tags %}
<nav class="navbar navbar-expand-lg navbar-light {% if SHIFTER_TEST_INSTANCE %}bg-danger{% else %}bg-light{% endif %}">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#shifterNavBar" aria-controls="shifterNavBar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="shifterNavBar">
            <a class="navbar-brand" href="{% url 'shifter:index' %}">{{ APP_NAME }}</a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- On shift now -->
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'today' %}active{% endif %}" href="{% url 'today' %}">
                        <div class="d-flex flex-column align-items-center">
                            <i class="fa-solid fa-users-between-lines fa-1x"></i>
                            <span class="text-center">Now on shift</span>
                        </div>
                    </a>
                </li>
                <!-- Overview -->
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}" href="{% url 'index' %}">
                        <div class="d-flex flex-column align-items-center">
                            <i class="fa-solid fa-calendar-days fa-1x"></i>
                            <span class="text-center">Overview</span>
                        </div>
                    </a>
                </li>

                {% if request.resolver_match.view_name != 'shifter:shift-edit' and request.resolver_match.view_name != 'shifter:shift-view' %}
                    <!-- Team List -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <div class="d-flex flex-column align-items-center">
                                <i class="fa-solid fa-people-group fa-1x"></i>
                                <span class="text-center">Team View</span>
                            </div>
                        </a>
                        <ul class="dropdown-menu {% if request.resolver_match.url_name == 'team-simple' %}active{% endif %}">
                            {% for a_team in teams %}
                                <li><a class="dropdown-item text-center" href="{% url 'team_view' team_id=a_team.id %}">
                                    {% if user.team == a_team %}<strong>{% endif %}
                                    {{ a_team.name }}
                                    {% if user.team == a_team %}</strong>{% endif %}
                                </a></li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}

                <!-- Assets and study Link (Login Required) -->
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'assets' %}active{% endif %}" href="{% url 'assets' %}">
                        <div class="d-flex flex-column align-items-center">
                            <i class="fa-solid fa-screwdriver-wrench fa-1x"></i>
                            <span class="text-center">Assets</span>
                        </div>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'study_request' %}active{% endif %}" href="{% url 'studies:study_request' %}">
                        <div class="d-flex flex-column align-items-center">
                            <i class="fa-solid fa-graduation-cap fa-1x"></i>
                            <span class="text-center">Studies</span>
                        </div>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'users' %}active{% endif %}" href="{% url 'users' %}">
                        <div class="d-flex flex-column align-items-center">
                            <i class="fa-solid fa-users-viewfinder fa-1x"></i>
                            <span class="text-center">Users Planning</span>
                        </div>
                    </a>
                </li>
                <li class="nav-item position-relative">
                    <a class="nav-link {% if request.resolver_match.url_name == 'shifts_market' %}active{% endif %}" href="{% url 'shifts_market' %}">
                        <div class="d-flex flex-column align-items-center">
                            <i class="fa-solid fa-store fa-1x"></i>
                            <span class="text-center">Shift Market</span>
                            {% if shift_count > 0 %}
                                <span class="badge bg-danger position-absolute top-0 start-100 translate-middle badge rounded-pill">{{ shift_count }}</span>
                            {% endif %}
                        </div>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'oncall_log' %}active{% endif %}" href="{% url 'oncall:oncall_log' %}">
                        <div class="d-flex flex-column align-items-center">
                            <i class="fa-solid fa-headset fa-1x"></i>
                            <span class="text-center">On-Call Log</span>
                        </div>
                    </a>
                </li>
                {% endif %}

                <!-- Rota-maker Link (Rota-maker role required) -->
                {% if request.resolver_match.view_name != 'shifter:shift-edit' and request.resolver_match.view_name != 'shifter:shift-view' %}
                    {% if rota_maker_for %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <div class="d-flex flex-column align-items-center">
                                <i class="fa-solid fa-user-tie fa-1x"></i>
                                <span class="text-center">Rota-maker</span>
                            </div>
                        </a>
                        <ul class="dropdown-menu {% if request.resolver_match.url_name == 'desiderata.team_view' %}active{% endif %}">
                            {% for a_managed_team in rota_maker_for %}
                                <li><a class="dropdown-item text-center" href="{% url 'desiderata.team_view' team_id=a_managed_team.id %}">
                                    {% if user.team == a_managed_team %}<strong>{% endif %}
                                    {{ a_managed_team.name }}
                                    {% if user.team == a_managed_team %}</strong>{% endif %}
                                </a></li>
                            {% endfor %}
                            <hr class="dropdown-divider">
                            <li><a class="dropdown-item text-center" href="{% url 'shift-upload' %}">Upload planning</a></li>
                        </ul>
                    </li>
                    {% endif %}
                {% endif %}
            </ul>

            {% if request.resolver_match.view_name != 'shifter:shift-edit' and request.resolver_match.view_name != 'shifter:shift-view' %}
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <div id="remote" data-source-url='{% url "ajax.search" %}'>
                        <input type="text" name="search_field" id="search_field" class="form-control input-lg typeahead" placeholder="Search" />
                    </div>
                    <!-- user authentication part -->
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown dropstart">
                        <a class="nav-link dropdown-toggle d-flex align-items-center m-0 p-0 ps-3" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img class="rounded-circle" loading="lazy" height="35" src={% if request.user.photo|length > 0 %} "data:image/gif;base64,{{request.user.photo}}" {% else %} {% static 'img/anonymous.png' %} {% endif %} />
                            {% live_notify_badge badge_class="badge" %}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'user' %}">My Shifts</a></li>
                            <li><a class="dropdown-item" href="{% url 'my_team_view' %}">My Team</a></li>
                            <li><a class="dropdown-item" href="{% url 'desiderata.user' %}">My Desiderata</a></li>
                            <li><a class="dropdown-item" href="{% url 'user' %}?notifications">Manage notifications {% live_notify_badge badge_class="badge" %}</a></li>
                            {% if user.is_superuser %}
                                <li><hr class="dropdown-divider"></li>
                                <a class="dropdown-item" href="{% url 'admin:index' %}">Administration</a>
                            {% endif %}
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            </li>
                        </ul>
                    </li>
                    {% else %}
                        <a class="btn btn-outline-success ms-2 mt-2" href="{% url 'login' %}" role="button">Login</a>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

<style>
    .nav-link {
            color: #000000; /* Icons color */
            transition: color 0.3s, background-color 0.3s, transform 0.3s;
            display: flex;
            align-items: center;
            padding: 0.5rem 1rem; /* Adjust padding as needed */
    }
</style>

shifts/templates/layout/person_id_card.html
{%  load static %}

<div class="col-md-3">
    <div class="contact-box center-version">
        <div>
            <img alt="image" class="rounded-circle" src={% if shift.member.photo|length > 0 %} "data:image/gif;base64,{{shift.member.photo}}" {%  else %} {% static 'img/anonymous.png'%} {% endif %}/>
            <h2 class="m-b-xs"><strong>{{ shift.member.name }}</strong></h2>
            <h5><span class="badge bg-secondary">{{ shift.real_role }}</span></h5>

        </div>
        {%  if shift.member.mobile or shift.member.email %}
        <div class="contact-box-footer">
            {%  if shift.member.mobile %}
            <div class="contact-box-link">
                <a href="tel:{{ shift.member.mobile }}">
                    <span class="fa-stack fa-x">
                        <i class="fa-solid fa-circle fa-stack-2x" style="color:#198754"></i>
                        <i class="fa-solid fa-phone fa-stack-1x fa-inverse"></i>
                    </span>
                    {{ shift.member.mobile }}
                </a>
            </div>
            {%  endif %}
            {%  if shift.member.email %}
            <div class="contact-box-link">
                <small>
                <a href="mailto:{{ shift.member.email }}">
                    <span class="fa-stack fa-x">
                        <i class="fa-solid fa-circle fa-stack-2x" style="color:#198754"></i>
                        <i class="fa-solid fa-mail-bulk fa-stack-1x fa-inverse"></i>
                    </span>
                    {{ shift.member.email }}
                </a>
                </small>
            </div>
            {%  endif %}
        </div>
        {%  endif %}
    </div>
</div>

shifts/templates/layout/phones.html
<div class="fab-container">
    <div class="fab fab-icon-holder">
        <i class="fa fa-phone-volume fa-flip-horizontal"></i>
    </div>
    <ul class="fab-options">
    {%  for a_very_important_person in operation_crew %}
    <li>
        <span class="fab-label">{{ a_very_important_person.real_role }} : {{ a_very_important_person.member }}</span>
        <div class="fab-icon-holder">
            <a href="tel:{{ a_very_important_person.member.mobile }}"> <i class="fa fa-phone fa-flip-horizontal"></i></a>
        </div>
    </li>
    {%  endfor %}
    <li>
        <span class="fab-label">MCR</span>
        <div class="fab-icon-holder">
           <a href="tel:{{ controlRoomPhoneNumber }}"> <i class="fa fa-phone fa-flip-horizontal"></i></a>
        </div>
    </li>
    {%  for contact in useful_contact %}
    <li>
        <span class="fab-label">{{ contact.name }}</span>
        <div class="fab-icon-holder">
           <a href="{{ contact }}" target="_blank"> <i class="fa {{ contact.fa_icon }} fa-flip-horizontal"></i></a>
        </div>
    </li>
    {%  endfor %}
    </ul>
</div>